/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = process.env.NEXT_PUBLIC_SUPABASE_PROJECT_ID || "bvskariztwghtlfueuml"
export const publicAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ""